id: P000129
initial_creation_type: ebook
source_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - མཛད་པ་པོ། མི་ཕམ་འཇམ་དབྱངས་རྒྱ་མ་ཆོ།
  layers:
  - book_title
  - author
  - tsawa
  - quotation
  - sabche
  id: RDI-SS-11-1
web_metadata:
  title:
    en: The Banquet of Supreme Mahayana Nectar:An Explanation of the Intent of “The
      Ornament of the Collection of the Mahayana Sutras,” Part 1
    bo: མདོ་སྡེའི་རྒྱན་གྱི་རྣམ་བཤད་བདུད་རྩིའི་དགའ་སྟོན། སྟོད་ཆ།
  collection:
    en: RDI Study Series–  Book 11 (Volume 1)
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༡༡-༡
  author:
    en: Jamgon Mipham Gyatso
    bo: འཇམ་མགོན་མི་ཕམ་རྒྱ་མཚོ།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-11-1
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-11-1.epub
  description:
    en: ༄༅། །ཤིང་རྟའི་སྲོལ་འབྱེད་ཆེན་མོ་འཕགས་པ་ཐོགས་མེད་ཀྱིས་ཆོས་རྒྱུན་གྱི་ཏིང་འཛིན་བརྙེད་ནས།
      དགའ་ལྡན་ཆོས་ཀྱི་ཕོ་བྲང་དུ་རྒྱལ་ཚབ་མི་ཕམ་མགོན་པོའི་ཞལ་ནས་དངོས་སུ་ནོད་པའི་བྱམས་ཆོས་སྡེ་ལྔའི་ཡ་གྱལ་ཐེག་པ་ཆེན་པོའི་མདོ་སྡེའི་རྒྱན་གྱི་གཞུང་ཁྱད་འཕགས་འདི་ཉིད་ཤིན་ཏུ་གསལ་བར་གོ་བདེ་བའི་ཚུལ་དུ་རྣམ་པར་བཤད་པ་བཞུགས་སོ།
      །
    bo: ༄༅། །ཤིང་རྟའི་སྲོལ་འབྱེད་ཆེན་མོ་འཕགས་པ་ཐོགས་མེད་ཀྱིས་ཆོས་རྒྱུན་གྱི་ཏིང་འཛིན་བརྙེད་ནས།
      དགའ་ལྡན་ཆོས་ཀྱི་ཕོ་བྲང་དུ་རྒྱལ་ཚབ་མི་ཕམ་མགོན་པོའི་ཞལ་ནས་དངོས་སུ་ནོད་པའི་བྱམས་ཆོས་སྡེ་ལྔའི་ཡ་གྱལ་ཐེག་པ་ཆེན་པོའི་མདོ་སྡེའི་རྒྱན་གྱི་གཞུང་ཁྱད་འཕགས་འདི་ཉིད་ཤིན་ཏུ་གསལ་བར་གོ་བདེ་བའི་ཚུལ་དུ་རྣམ་པར་བཤད་པ་བཞུགས་སོ།
      །
